apiVersion: v1
kind: Service
metadata:
  name: {{ include "opnode.fullname" . }}
  labels:
    {{- include "opnode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8545
      targetPort: opgeth-rpc
      protocol: TCP
      name: opgeth-rpc
    - port: 8546
      targetPort: opgeth-rpc
      protocol: TCP
      name: opgeth-rpc
    - port: 9545
      targetPort: opnode-rpc
      protocol: TCP
      name: opnode-rpc
  selector:
    {{- include "opnode.selectorLabels" . | nindent 4 }}
