apiVersion: v1
kind: Service
metadata:
  name: {{ include "opnode.fullname" . }}
  labels:
    {{- include "opnode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 30303
      targetPort: opgeth-p2p
      protocol: TCP
      name: opgeth-p2p
    - port: 30304
      targetPort: opgeth-discovery
      protocol: TCP
      name: opgeth-discovery
    - port: 30303
      targetPort: opnode-p2p
      protocol: TCP
      name: opnode-p2p
    - port: 30304
      targetPort: opnode-discovery
      protocol: TCP
      name: opnode-discovery
  selector:
    {{- include "opnode.selectorLabels" . | nindent 4 }}
