# {{- if gt (int .Values.replicas) 1 }}
#   {{ required "HA redis must be configured" .Values.redis }}
# {{- end }}

# {{ required "proxyd.nodes must be added." .Values.proxyd.nodes }}
# {{ required "dugtrio.nodes must be added." .Values.dugtrio.nodes }}

# {{- if .Values.vmPodScrape.enabled }}
#   {{ required "vmPodScrape.region must be set." .Values.vmPodScrape.region }}
# {{- end }}
