# -- Overrides the chart's name
nameOverride: ""

# -- Overrides the chart's computed fullname
fullnameOverride: ""

reth:
  image:
    repository: ghcr.io/paradigmxyz/reth
    # -- Nimbus image tag
    tag: v1.3.12
  resources:
    # -- Nimbus resource requests and limits
    requests:
      cpu: 2
      memory: 16Gi
    limits:
      # cpu: 500m
      memory: 24Gi

nimbus:
  image:
    repository: statusim/nimbus-eth2
    # -- Nimbus image tag
    tag: amd64-v25.4.0
  resources:
    # -- Nimbus resource requests and limits
    requests:
      cpu: 1
      memory: 8Gi
    limits:
      # cpu: 500m
      memory: 12Gi

# -- Number of replicas
replicas: 1
ethereumChain: sepolia
p2pNlb:
  #* AWS EIP to attach to NLB exposing p2p ports
  eIPs: []
  #* Security group to attach to NLB exposing p2p ports
  securityGroup: AWS-Security-Group
  #* Subnet name without az name, subnets should be named in the following way: `${publicSubnetPrefix}-${azName}`.
  subnetPrefix: AWS-Subnet-Prefix

dataSnapshot:
  # -- Backup enabled
  restoreData: false
  # -- Backup schedule
  schedule: "0 0 * * *"
  # -- Backup retention
  retention: 7
  # -- Backup bucket name
  bucketName: ""
  # -- Backup bucket region
  bucketRegion: ""
  # -- Backup bucket prefix
  bucketPrefix: ""

pullPolicy: IfNotPresent

# -- Extra args for the reth container
extraArgs: []
  #- --network=holesky

ingress:
  # -- Ingress resource for the HTTP API
  enabled: false
  # -- Annotations for Ingress
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- Ingress host
  hosts:
    - host: chart-example.local
      paths: []
  # -- Ingress TLS
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Affinity configuration for pods
affinity: {}

# -- Image pull secrets for Docker images
imagePullSecrets: []

# -- Annotations for the StatefulSet
annotations: {}

# -- Liveness probe
# # @default -- See `values.yaml`
# livenessProbe:
#   tcpSocket:
#     port: http-rpc
#   initialDelaySeconds: 60
#   periodSeconds: 120

# # -- Readiness probe
# # @default -- See `values.yaml`
# readinessProbe:
#   tcpSocket:
#     port: http-rpc
#   initialDelaySeconds: 10
#   periodSeconds: 10

# -- Node selector for pods
nodeSelector: {}

persistence:
  size: 20Gi
  storageClassName: null

# -- Pod labels
podLabels: {}

# -- Pod annotations
podAnnotations: {}

# -- Pod management policy
podManagementPolicy: OrderedReady

# -- Pod priority class
priorityClassName: null

rbac:
  # -- Specifies whether RBAC resources are to be created
  create: true
  rules:
    # Required to get information about the services nodePort.
    - apiGroups: [""]
      resources:
      - services
      verbs:
      - get
      - list
      - watch

# -- Resource requests and limits
resources: {}
# limits:
#   cpu: 500m
#   memory: 2Gi
# requests:
#   cpu: 300m
#   memory: 1Gi

# -- The security context for pods
# @default -- See `values.yaml`
securityContext:
  fsGroup: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  runAsUser: 10001

# -- The security context for containers
# @default -- See `values.yaml`
containerSecurityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- How long to wait until the pod is forcefully terminated
terminationGracePeriodSeconds: 90

# # -- Tolerations for pods
# ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
# tolerations: []

# # -- Topology Spread Constraints for pods
# ## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
# topologySpreadConstraints: []

tolerations:
  - effect: NoSchedule
    key: lvm-localpv
    operator: Equal
    value: "true"

topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        statefulsetname: node
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule



# -- Define the PodDisruptionBudget spec
# If not set then a PodDisruptionBudget will not be created
podDisruptionBudget: {}
# minAvailable: 1
# maxUnavailable: 1

# -- Update strategy for the Statefulset
updateStrategy:
  # -- Update strategy type
  type: RollingUpdate

# -- Additional volumes
extraVolumes: []

# -- Additional volume mounts
extraVolumeMounts: []

# -- Additional ports. Useful when using extraContainers or extraContainerPorts
extraPorts: []

# -- Additional ports for the main container
extraContainerPorts: []

# -- Additional env variables
extraEnv: []

# -- Additional env variables injected via a created secret
secretEnv: {}
# MY_PASSWORD: supersecret

# initChownData:
#   # -- Init container to set the correct permissions to access data directories
#   enabled: true
#   image:
#     # -- Container repository
#     repository: busybox
#     # -- Container tag
#     tag: 1.34.0
#     # -- Container pull policy
#     pullPolicy: IfNotPresent
#   # -- Resource requests and limits
#   resources: {}
#   #  limits:
#   #    cpu: 100m
#   #    memory: 128Mi
#   #  requests:
#   #    cpu: 100m
#   #    memory: 128Mi

serviceMonitor:
  # -- If true, a ServiceMonitor CRD is created for a prometheus operator
  # https://github.com/coreos/prometheus-operator
  enabled: false
  # -- Path to scrape
  path: /debug/metrics/prometheus
  # -- Alternative namespace for ServiceMonitor
  namespace: null
  # -- Additional ServiceMonitor labels
  labels: {}
  # -- Additional ServiceMonitor annotations
  annotations: {}
  # -- ServiceMonitor scrape interval
  interval: 1m
  # -- ServiceMonitor scheme
  scheme: http
  # -- ServiceMonitor TLS configuration
  tlsConfig: {}
  # -- ServiceMonitor scrape timeout
  scrapeTimeout: 30s
  # -- ServiceMonitor relabelings
  relabelings: []



# -- Template used for the default command
# @default -- See `values.yaml`
# defaultCommandTemplate: |
#   - sh
#   - -ac
#   - >
#   {{- if .Values.p2pNodePort.enabled }}
#     . /env/init-nodeport;
#   {{- end }}
#     exec /usr/local/bin/reth node
#     --datadir=/data
#     --config=/data/config.toml
#   {{- if .Values.p2pNodePort.enabled }}
#     {{- if not (contains "--nat=" (.Values.extraArgs | join ",")) }}
#     --nat=extip:$EXTERNAL_IP
#     {{- end }}
#     {{- if not (contains "--port=" (.Values.extraArgs | join ",")) }}
#     --port=$EXTERNAL_PORT
#     {{- end }}
#   {{- else }}
#     {{- if not (contains "--nat=" (.Values.extraArgs | join ",")) }}
#     --nat=extip:$(POD_IP)
#     {{- end }}
#     {{- if not (contains "--port=" (.Values.extraArgs | join ",")) }}
#     --port={{ include "reth.p2pPort" . }}
#     {{- end }}
#   {{- end }}
#     --http
#     --http.addr=0.0.0.0
#     --http.port={{ .Values.httpPort }}
#     --http.corsdomain=*
#     --ws
#     --ws.addr=0.0.0.0
#     --ws.port={{ .Values.wsPort }}
#     --ws.origins=*
#     --authrpc.jwtsecret=/data/jwt.hex
#     --authrpc.addr=0.0.0.0
#     --authrpc.port={{ .Values.authPort }}
#     --log.file.directory=/data/logs
#   {{- if .Values.metricsPort }}
#     --metrics=0.0.0.0:{{ .Values.metricsPort }}
#   {{- end }}
#   {{- range .Values.extraArgs }}
#     {{ tpl . $ }}
#   {{- end }}

# # -- Legacy way of overwriting the default command. You may prefer to change defaultCommandTemplate instead.
# customCommand: []

# When p2pNodePort is enabled, your P2P port will be exposed via service type NodePort.
# This is useful if you want to expose and announce your node to the Internet.
# Limitation: You can only one have one replica when exposing via NodePort.
#             Check the chart README.md for more details
# p2pNodePort:
#   # -- Expose P2P port via NodePort
#   enabled: false
#   # -- NodePort to be used
#   port: 31000
#   initContainer:
#     image:
#       # -- Container image to fetch nodeport information
#       repository: lachlanevenson/k8s-kubectl
#       # -- Container tag
#       tag: v1.25.4
#       # -- Container pull policy
#       pullPolicy: IfNotPresent
#   portForwardContainer:
#     image:
#       # -- Container image for the port forwarder
#       repository: alpine/socat
#       # -- Container tag
#       tag: latest
#       # -- Container pull policy
#       pullPolicy: IfNotPresent
