#! if sequencer, then
#!   0. 
  # genesisURL                    - in chain.yaml
  # rollup.json                   - in chain.yaml
#!   1. NodePort
  # opGethAdvertiseTcpPort: 32201 - in values
  # opNodeAdvertiseTcpPort: 32221 - in values
  #? netRestrictCIDR: 10.0.0.0/8 ?? - in values
#!   2. Only the sequencers are the peers
  # sequencersOpGethAddresses: [] - in chain.yaml
  # sequencersOpNodeAddresses: [] - in chain.yaml
#!   3. ExternalSecrets
  # externalSecretRoleARN           - in `environment.yaml` ?? naming convention
  # sequencerOpNodeP2PKeySecretName - $chainName-$Namespace  dev-hari-sequencer-1-opnode-p2p
  # sequencerOpGethP2PKeySecretName - $chainName-$Namespace  dev-hari-sequencer-1-opgeth-p2p
  # sequencerPrivateKeySecretName   - $chainName-$Namespace  dev-hari-sequencers-private-key
#!   4. Internal ingress
  # securityGroup        - in `environment.yaml`
  # accessLogsS3         - in `environment.yaml`
  # internalDnsZone      - in `environment.yaml`
#!   5. replicas =1
      sources:
        - repoURL: https://github.com/Soneium/soneium-infra-gitops.git
          path: "{{.path.path}}"
          targetRevision: stg-infra
          helm:
            parameters:
              - name: environment
                value: dev-hari
            valuesObject:
              #* {{ tpl (printf "values/%s" $valuesFile | $.Files.Get) $ | indent 10 }}
              #* sequencer.yaml
              sequencer: true    
              opGethAdvertiseTcpPort: 32201
              opNodeAdvertiseTcpPort: 32221
              netRestrictCIDR: 10.0.0.0/8

              externalSecretRoleARN: {{(get .Values .cluster.argoCluster).sequencer-1.externalSecretRoleARN}}
              securityGroup: {{(get .Values .cluster.argoCluster).securityGroup}}
              accessLogsS3: {{(get .Values .cluster.argoCluster).accessLogsS3}}
              internalDnsZone: {{(get .Values .cluster.argoCluster).internalDnsZone}}




              # The AWS region for the kubernetes cluster. Set to use KIAM or kube2iam for example.
              region: {{(get .Values .cluster.argoCluster).eksRegion}}

            valueFiles:
            - $values/$ENV/chain.yaml
            - $values/$ENV/environment.yaml
        - repoURL: https://github.com/Soneium/soneium-infra-gitops.git
          targetRevision: stg-infra
          ref: values




#! If Peer
#!   1. LoadBalancer service
  # nlbSubnetPrefix: subnets preffix - in `environment.yaml`
  # eip list        - in `environment.yaml`
  # securityGroup        - in `environment.yaml`
#!   2. Sequencer URL ??? any or active ???
  # sequencer rpc URL (only if snap ???)
#!   3. ExternalSecrets
  # extSecretRoleARN - can get secrets of any peer
  # p2pKeySecretPrefix - just chain name (dev-hari-....)
#?   4. Ingress
  # securityGroup        - in `environment.yaml`
  # accessLogsS3         - in `environment.yaml`
  #? internalDnsZone      - in `environment.yaml`
#!   5. replicas >1
