apiVersion: v2
name: uni-helm
description: A Helm chart for Kubernetes

keywords:
  - blockchain
  - web3

maintainers:
  - email: vlad.sh@startale.com
  - email: marijan.cavar@startale.com

type: application

version: 1.0.0
